required = ["github.com/golang/dep","github.com/wadey/gocovmerge","github.com/mattn/goveralls","github.com/fatih/gomodifytags","github.com/tmthrgd/go-bindata/go-bindata","github.com/cheekybits/genny","github.com/alvaroloes/enumer","github.com/GoASTScanner/gas/cmd/gas","github.com/alecthomas/gometalinter"]
requirements = ["github.com/golang/dep","github.com/wadey/gocovmerge","github.com/mattn/goveralls","github.com/tmthrgd/go-bindata/go-bindata","github.com/GoASTScanner/gas/cmd/gas","github.com/alecthomas/gometalinter"]

[[constraint]]
  name = "github.com/golang/dep"
  version = "0.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/wadey/gocovmerge"

[[constraint]]
  name = "github.com/mattn/goveralls"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/tmthrgd/go-bindata"

[[constraint]]
  branch = "issue/153"
  name = "github.com/GoASTScanner/gas"

[[constraint]]
  name = "github.com/alecthomas/gometalinter"
  version = "2.0.6"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v3-unstable"
  revision = "63abe20a23e29e80bbef8089bd3dee3ac25e5306"

[prune]
  go-tests = true
  unused-packages = true
